version: '3'
services:
  mongo-app:
    build:
      context: ./docker/golang
      dockerfile: Dockerfile
      args:
        - VARIANT=1.16
        - INSTALL_NODE=true
        - NODE_VERSION=lts/*
    container_name: mongo-app
    volumes:
      - ../:/go/github.com/MasatoTokuse/mongo-go-example
    working_dir: /go/github.com/MasatoTokuse/mongo-go-example
    tty: true
    stdin_open: true
    command: /bin/bash
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    env_file:
      - ./docker/mongo/mongo.env
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example